# Modified this file for takeon-data-prep-py-lambda
# For full config options, check the docs:
#    docs.serverless.com


service: takeon-data-prep-py-lambda

provider:
  name: aws
  runtime: python3.7
  profile: sls-admin
  region: eu-west-2

functions:
  run_data_prep:
    handler: handler.run_data_prep
    role: ${file(./config.dev.json):ROLE}
    layers:
      - ${file(./config.dev.json):LAYER_NAME}
    environment:
      DATABASE_USER: ${file(./config.dev.json):DB_USER}
      DATABASE_PASSWORD: ${file(./config.dev.json):DB_PW}
      DATABASE_HOST: ${file(./config.dev.json):DB_HOST}
      DATABASE_NAME: ${file(./config.dev.json):DB_NAME}
      WRANGLER_NAME: wrangler-lambda
    vpc:
      securityGroupIds:
        - ${file(./config.dev.json):SECURITY_GROUP_ID}
      subnetIds:
        - ${file(./config.dev.json):SUBNET_ID}
    timeout: 30

package:
  exclude:
  - venv/**
  - .vscode/**
  - .cache/**
  - test/**
  - Docs/**




